// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Map<String, String>> getHeadInfoRust(
        {required String url, required Map<String, String> headers}) =>
    RustLib.instance.api
        .crateApiDownloadGetHeadInfoRust(url: url, headers: headers);

Stream<Uint8List> downloadChunkRust(
        {required String url,
        required BigInt start,
        required BigInt end,
        required Map<String, String> headers}) =>
    RustLib.instance.api.crateApiDownloadDownloadChunkRust(
        url: url, start: start, end: end, headers: headers);
